### ISSUE TITLE
ImatPro API definition

### ISSUE THREAD

**Issue by josedanielhernandezosorio** [josedanielhernandezosorio/backend_imatpro_system#6]
Que tal Amigo se que es mu pronto pera para no pasar alto la documentacion de las apis que vayamos asiendo la podemos ir asiendo con esta herramienta : [https://swagger.io/tools/swagger-editor/](url)

**Comment by Sofyntelligen** [comment]
Se agrega los enpoint, para la extraccion de la informacion, queda pendiente el manejo de la paginacion para el control de la informacion.

![Captura de pantalla 2023-03-28 a la(s) 8 41 22](https://user-images.githubusercontent.com/11186941/228275361-3d01b5de-bc97-46f6-bfaa-bd69c5592bbf.png)
